### ISSUE TITLE
modify the equation in the text

### ISSUE THREAD

**Issue by ncparker** [peteWT/cec_apl#1]
@peteWT Please change the equation to the following: 

if:
    merch_val_dpa - (harvest_onsite_cpa + haul_merch_cpa) >= 0
then:
    chip_price_dpa = 0
else:
    chip_price_dpa = merch_val_dpa - (harvest_onsite_cpa + haul_merch_cpa)

To get biomass price (in $/green ton), you need to divide the chip_price_dpa by chip_yield_gt.

**Comment by peteWT** [comment]
Thanks @ncparker !

**Comment by jd-lara** [comment]
Just a quick correction on the formula, in the first if. 

if:
merch_val_dpa - (harvest_onsite_cpa + haul_merch_cpa) <= 0
then:
chip_price_dpa = 0
else:
chip_price_dpa = merch_val_dpa - (harvest_onsite_cpa + haul_merch_cpa)
