### ISSUE TITLE
Files from the raster

### ISSUE THREAD

**Issue by jd-lara** [peteWT/cec_apl#4]
@carmentubbesing I am trying to run your code in R but I can't get passed the call for the files. I get this error: 

> LEMMA <- raster("mr200_2012")
> Error in .local(.Object, ...) : 
>   `/Users/jdlara/Documents/Box Sync/EPIC-Biomass/GIS Data/LEMMA_gnn_sppsz_2014_08_28/mr200_2012' not recognised as a supported file format.

Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.

For some reason mr200_2012 is recognized as a folder not a file.

**Comment by carmentubbesing** [comment]
Hey Jose, I'm not sure why you're having that issue since it worked fine on my machine, but you shouldn't need to execute that line in order to test the rest of the code, since I cropped the raster data in mr200_2012 and re-saved it as LEMMA.gri in order to cut down on processing time every time I want to open that data.

**Comment by jd-lara** [comment]
@carmentubbesing I have no LEMMA.gri file in my box folder. Just the LEMMA.grd

**Comment by jd-lara** [comment]
@carmentubbesing, the R code failed again but now is this result

> result.p <- ploop(1, nrow(drought_bu))
> Error in drought[i, ] : 
>   cannot get a slot ("Polygons") from an object of type "NULL"

**Comment by carmentubbesing** [comment]
I believe the error is because you didn't redefine `drought` as `drought_bu` so `drought` is shorter than `drought_bu`, giving an error in the line `single <- drought[i,]`. I commented out the line that crops `drought`, so now if you run the whole thing from the top up until line 184, you should be good.

**Comment by jd-lara** [comment]
Hi @carmentubbesing , the code ran for about 2.5 hrs and then it failed again. I am not sure what I might need to debug it further. Can we do a data rationality check?

> result.p <- ploop(1, nrow(drought))
>   Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column 
> 6 stop(ngettext(sum(bad), "'by' must specify a uniquely valid column", 
>     "'by' must specify uniquely valid columns"), domain = NA) 
> 5 fix.by(by.x, x) 
> 4 merge.data.frame(mat, mat2, by = "Var1") 
> 3 merge(mat, mat2, by = "Var1") 
> 2 merge(mat, mat2, by = "Var1") 
> 1 ploop(1, nrow(drought)) 

I believe the problem is in the execution of this line, when you perform the merge 

merge <- merge(L.in.mat, mat2, by.y = "Var1", by.x = "ID") # merge LEMMA data with polygon data into one table

**Comment by carmentubbesing** [comment]
@jdlara-berkeley, what's a rationality check?

**Comment by jd-lara** [comment]
@carmentubbesing just means that we have to check wether the data going into the function is correct. It seems to me that the problem is that when we pass the information into the function is invalid.

**Comment by carmentubbesing** [comment]
@jdlara-berkeley Ok. Do you want me to do that or do you want to do that?

**Comment by jd-lara** [comment]
@carmentubbesing I don't know how to do that in R, I tried last night without sucess.

**Comment by carmentubbesing** [comment]
@jdlara-berkeley I can try to look at it later today.

**Comment by jd-lara** [comment]
@carmentubbesing I have been following your code, the problem is located in `i = 6029L`. The variable `tab` returns a `NULL`, which makes `s`` to be 0. Later on`mat2``` is divided by 0 and returns a NULL. 

All of this makes de merge operation fail 

```
tab <- lapply(ext, table) # creates a table that counts how many of each raster value there are in the polygon
    s <- sum(tab[[1]]) # Counts total raster cells the polygon - this is different from length(clip2tg) because it doesn't include NAs
    mat <- as.data.frame(tab)
    mat2 <- as.data.frame(tab[[1]]/s) # gives fraction of polygon occupied by each plot type. Adds up to 1 for each polygon.
    mat2 <- merge(mat, mat2, by="Var1") #this is the line that fails. 
```

**Comment by carmentubbesing** [comment]
Hi @jdlara-berkeley, we added the fix for that but I guess it didn't make it onto github. I just pushed that script with the fix. I just added 

```
if (is.na(mat[1,1])) { 
  next 
}
```

at line 100.

**Comment by jd-lara** [comment]
@carmentubbesing now we have a new error 

> Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column 
> 6 stop(ngettext(sum(bad), "'by' must specify a uniquely valid column", 
>     "'by' must specify uniquely valid columns"), domain = NA) 
> 5 fix.by(by.x, x) 
> 4 merge.data.frame(mat, mat2, by = "Var1") 
> 3 merge(mat, mat2, by = "Var1") 
> 2 merge(mat, mat2, by = "Var1") 
> 1 ploop(1, nrow(drought)) 

I will check how to debug it.

**Comment by jd-lara** [comment]
The problem is happening in the same index `i=6029L` it seems that the problem appears in the line `mat2 <- merge(mat, mat2, by="Var1")` still related to the problem of s = 0

**Comment by carmentubbesing** [comment]
What version of the code are you using? How recently did you pull?

**Comment by jd-lara** [comment]
3 hours ago.

**Comment by carmentubbesing** [comment]
When I run the loop over those polygons, it skips the ones with s = 0:

```
> test <- ploop(6028,6035)
> unique(test$Pol.ID)
[1] 6035 6034 6033 6028
```

The only thing I can think of that could be happening is that you're using a version of the code that doesn't have the fix I made earlier today.

**Comment by jd-lara** [comment]
I merged the two versions, let me check if all is ok. 

Jose Daniel Lara
+1 510 502 6238
ca.linkedin.com/pub/jose-daniel-lara/57/7b4/318/

**Comment by carmentubbesing** [comment]
Ok. Please push the merged version when you can so that I can make some small changes to it.

**Comment by jd-lara** [comment]
I pushed it, let me know when you do the merge  to start a run before I
leave tonight

On Sep 2, 2016 4:29 PM, "carmentubbesing" notifications@github.com wrote:

Ok. Please push the merged version when you can so that I can make some
small changes to it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/peteWT/cec_apl/issues/4#issuecomment-244509708, or mute
the thread
